### ISSUE TITLE
楼主这篇博里面提到的QQ群号是多少？

### ISSUE THREAD

**Issue by zwl1619** [resona/PingLunShuJu#123]
楼主这篇博里面提到的QQ群号是多少？
《clash搭建科学梯子》https://resona.top/2021/03/25/clash%E6%90%AD%E5%BB%BA%E8%87%AA%E7%94%B1%E4%B8%8A%E7%BD%91/

**Comment by resona** [comment]
> 楼主这篇博里面提到的QQ群号是多少？ 《clash搭建科学梯子》https://resona.top/2021/03/25/clash%E6%90%AD%E5%BB%BA%E8%87%AA%E7%94%B1%E4%B8%8A%E7%BD%91/

兄弟，这个群已经解散很久了，你如果是想科学上网的话，我推荐你用https://glados.rocks/ 我一直用的这个，还挺好用的
